### ISSUE TITLE
Possible problem with VHM and six_payment example

### ISSUE THREAD

**Issue by marfago** [bluedynamics/bda.plone.payment#3]
Hi,

My current installation uses a virtual host monster approach in order to rewrite the incoming requests from the outside form to the locally managed form, i.e. from www.mysite.com to localhost:myport/mysite.
While using the the internal URLs all works fine and I can see the test page from the bank for the online payment process, when accessing the site through VHM the host in the link returned by the bank is replaced with mysite host, i.e. 
www.mybank.com/xxxx?paymentId=yyyy becomes www.mysite.com/xxxx?paymentId=yyyy. 

Im pretty sure it is due to the VHM replacement logic which simply replaces blindly the host part in the URL with the site host. 

Is there anyway to workaround this issue (f.i. disabling vhm for such an URL or using alternatives to zExceptions.Redirect)?

**Comment by rnixx** [comment]
Why not using nginx for virtual hosting?

**Comment by marfago** [comment]
Hi,

I'm not expert with zope/plone administration and whatever official guide I've found around on internet uses the Virtual Host approach. An example here

http://docs.plone.org/manage/deploying/front-end/nginx.html

Could you please point me to a way to configure zope/plone without VH?
Thanks

PS: BTW, current workaround is to use a simple page accepting the bank URL as a parameter and  redirecting (via javascript) to that URL.

**Comment by agitator** [comment]
Haven't had any problems like this.
Please reopen if still an issue.
